workflows:
    android-app:
        name: Android App
        instance_type: linux
        scripts:
            - name: Build Android APK
            working_directory: android
            script: ./gradlew assembleRelease
        artifacts:
            - app/build/outputs/**/**/*.apk
        publishing:
            email:
                recipients:
                    - csaikumar501@gmail.com
